backend:
  name: git-gateway
  repo: bryanalex9763-arch/rifx-marketing.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "config"
    label: "Configuración Web"
    files:
      - file: "data.json"
        label: "Textos de Inicio"
        name: "inicio"
        fields:
          - { label: "Título Principal", name: "title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
          - { label: "Texto Botón", name: "btn_text", widget: "string" }