backend:
  name: git-gateway
  repo: bryanalex9763-arch/rifx-marketing.github.io # Confirma que este sea tu usuario/repo
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas del Sitio"
    files:
      - file: "index.html"
        label: "Editar Página de Inicio"
        name: "index"
        fields:
          - { label: "Código HTML Completo", name: "body", widget: "code", default_language: "html" }