backend:
  name: git-gateway
  repo: bryanalex9763-arch/rifx-marketing.github.io
  branch: main

media_folder: "imágenes"
public_folder: "/imágenes"

collections:
  - name: "páginas"
    label: "Páginas"
    files:
      - file: "índice.html"
        label: "Inicio"
        name: "índice"
        fields:
          - { label: "Título Principal", name: "title", widget: "string" }
          - { label: "Descripción Hero", name: "description", widget: "text" }
          - { label: "Color de Fondo", name: "bg_color", widget: "color" }